version: '3.3'
services:
  app:
    container_name: XM-Task
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - db-dev
    networks:
      - XM-API
  db-dev:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'XM'
      MYSQL_USER: 'Test'
      MYSQL_PASSWORD: '24072017'
      MYSQL_ROOT_PASSWORD: '24072017'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
     - xm-db:/var/lib/mysql
  db-test:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'XM'
      MYSQL_USER: 'Test'
      MYSQL_PASSWORD: '24072017'
      MYSQL_ROOT_PASSWORD: '24072017'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - xm-test:/var/lib/mysql
volumes:
  api:
  xm-db:
  xm-test:
networks:
    XM-API:
      driver: bridge