version: '3.3'
services:
  app:
    container_name: XM-Task
    build: ..
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - XM-mysql
    networks:
      - XM-API
  XM-mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_HOST=${DB_HOST}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
     - xm-db:/var/lib/mysql
    networks:
     - XM-API
  db-test:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'XM'
      MYSQL_USER: 'Test'
      MYSQL_PASSWORD: '24072017'
      MYSQL_ROOT_PASSWORD: '24072017'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - xm-test:/var/lib/mysql
  XM-zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  XM-kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "activity_logs:1:1"
volumes:
  api:
  xm-db:
  xm-test:
networks:
    XM-API:
      driver: bridge